const categoriesActionsTypes = {
    FETCH_ALL_CATEGORIES_REQUEST: 'FETCH_ALL_CATEGORIES_REQUEST',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',
    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
};

export default categoriesActionsTypes;
