const categoriesActionsTypes = {
    CATEGORIES_REQUEST: 'CATEGORIES_REQUEST',
    CATEGORIES_FAILED: 'CATEGORIES_FAILED',

    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',

    FETCH_CATEGORY_BY_ID_SUCCESS: 'FETCH_CATEGORY_BY_ID_SUCCESS',
};

export default categoriesActionsTypes;
