const tasksActionsTypes = {
    TASKS_REQUEST: 'TASKS_REQUEST',
    TASKS_FAILED: 'TASKS_FAILED',

    FETCH_ALL_TASKS_SUCCESS: 'FETCH_ALL_TASKS_SUCCESS',

    UPDATE_TASKS_SUCCESS: 'UPDATE_TASKS_SUCCESS',
};

export default tasksActionsTypes;
